---
title: STAT 385 HW2
author: Joshua Zhao
date: '2020-03-09'
slug: stat-385-hw2
categories:
  - R
tags:
  - r
description: ''
images:
  - ''
type: post
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 1:

## (a)
```{r}
wheel = read.csv("https://nkha149.github.io/stat385-sp2020/files/data/roulette.csv")
wheel
```

```{r}
#install.packages("scales")
library(scales)
```

## (b)
```{r}
roulette = function(bet, amount = 1 ) {
   roulette = wheel[sample(1:nrow(wheel), size = 1), "number"]
   low = 1:18
   high = 19:36
   red = c(1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36)
   black = c(2, 4, 6, 8, 10, 11, 13, 15, 17, 20, 22, 24, 26, 28, 29, 31, 33, 35)
   odd = c()
   for (n in 1:18){odd[n]=2*n-1}
   even = c()
   for (n in 1:18){even[n]=2*n}
   first = 1:12
   second = 13:24
   third = 25:36
   
   account = amount
   
   if (bet == "red" | bet == "black"){
      if (bet=="red" & roulette %in% red){
     account = 1*account
      }
      else if (bet=="black" & roulette %in% black){
      account = 1*account
      }
      else {account = -amount
      }}
   
   if (bet== "high" | bet == "low"){
      if (bet == "high" & roulette %in% high){
     account = 1*amount
      }
      else if (bet == "low" & roulette %in% low){
      account = 1*amount
      }
   else {account = -1*amount}}
   
   if (bet== "odd" | bet == "even"){
      if (bet == "odd" & roulette %in% odd){
     account = 1*account
      }
      else if (bet == "even" & roulette %in% even){
      account = 1*account
      }
   else {account = -1*amount}}
   
   if (bet== "first" | bet == "second" | bet=="third"){
      if (bet == "first" & roulette %in% first){
     account = 2*amount
      }
      else if (bet == "second" & roulette %in% second){
      account = 2*amount
      }
      else if (bet == "third" & roulette %in% third){
      account = 2*amount
      }
   else {account = -2*amount}}
   
   if (is.numeric(bet)){
       if (bet==roulette){
      account = 36*amount
   }
   else {account = -amount}
   }
  
   
   #cat("$",account,seq="")
   ifelse(account < 0, paste0("-", dollar(abs(account))), dollar(account))
   }
   
```

```{r}
set.seed(385)
roulette(bet = "red", amount = 10)
```

```{r}
set.seed(385)
roulette(bet = "first", amount = 15)
```

```{r}
set.seed(385)
roulette(bet = "odd", amount = 20)
```

```{r}
set.seed(385)
roulette(bet = 9, amount = 10)
```

```{r}
set.seed(385)
roulette(bet = 5)
```

# Exercise 2

## (a)
```{r}
roulette2 = function(bet, amount = 1 ) {
   roulette = wheel[sample(1:nrow(wheel), size = 1), "number"]
   low = 1:18
   high = 19:36
   red = c(1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36)
   black = c(2, 4, 6, 8, 10, 11, 13, 15, 17, 20, 22, 24, 26, 28, 29, 31, 33, 35)
   odd = c()
   for (n in 1:18){odd[n]=2*n-1}
   even = c()
   for (n in 1:18){even[n]=2*n}
   first = 1:12
   second = 13:24
   third = 25:36
   
   account = amount
   
   if (bet == "red" | bet == "black"){
      if (bet=="red" & roulette %in% red){
     account = 1*account
      }
      else if (bet=="black" & roulette %in% black){
      account = 1*account
      }
      else {account = -amount
      }}
   
   if (bet== "high" | bet == "low"){
      if (bet == "high" & roulette %in% high){
     account = 1*amount
      }
      else if (bet == "low" & roulette %in% low){
      account = 1*amount
      }
   else {account = -1*amount}}
   
   if (bet== "odd" | bet == "even"){
      if (bet == "odd" & roulette %in% odd){
     account = 1*account
      }
      else if (bet == "even" & roulette %in% even){
      account = 1*account
      }
   else {account = -1*amount}}
   
   if (bet== "first" | bet == "second" | bet=="third"){
      if (bet == "first" & roulette %in% first){
     account = 2*amount
      }
      else if (bet == "second" & roulette %in% second){
      account = 2*amount
      }
      else if (bet == "third" & roulette %in% third){
      account = 2*amount
      }
   else {account = -2*amount}}
   
   if (is.numeric(bet)){
       if (bet==roulette){
      account = 36*amount
   }
   else {account = -amount}
   }
  
   account
   }
```

```{r}
set.seed(385)
roulette2(bet = "red", amount = 10)
```
```{r}
set.seed(385)
roulette2(bet = "first", amount = 15)
```
```{r}
set.seed(385)
roulette2(bet = "odd", amount = 20)
```
```{r}
set.seed(385)
roulette2(bet = 9, amount = 10)
```
```{r}
set.seed(385)
roulette2(bet = 5)
```

## (b)

```{r}
set.seed(385)
results = replicate(roulette2(bet = "red"), n=5000)
length(which(results==1))/5000
```

```{r}
set.seed(385)
results = replicate(roulette2(bet = "first"), n=5000)
length(which(results==2))/5000
```

## 
```{r}
set.seed(385)
results = replicate(roulette2(bet = "odd", amount=5), n=7500)
mean(results)
```


# Exercise 3

## (a)
```{r}
hist(x = iris$Sepal.Length, probability = TRUE, border = "dodgerblue",
     main = "Histogram of Sepal Length",
     xlab = "Sepal Length", breaks = 20)
grid()
box()
```

## (b)
```{r}
plot(formula = iris$Sepal.Width ~ iris$Sepal.Length, data = trees,
     main = "Iris Sepal Length vs. Sepal Width",
     xlab = "Sepal Length", ylab = "Sepal Width",
     col = "pink", pch = 19)
grid()
```

## (c)
```{r}
plot(formula = iris$Sepal.Width ~ iris$Sepal.Length, data = trees,
     main = "Iris Sepal Length vs. Sepal Width by Species",
     xlab = "Sepal Length", ylab = "Sepal Width",
     col = ifelse(iris$Species=="setosa", "black",ifelse(iris$Species=="versicolor","red",ifelse(iris$Species=="virginica","blue","yellow"))), pch = 19)
grid()
```



